version: "3"
services:
  postgres:
    image: "smoothiesjoint.azurecr.io/postgres:latest"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    # image: "smoothiesjoint.azurecr.io/api:latest"
    build: 
      dockerfile: Dockerfile
      context: .
    hostname: api
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    # image: "smoothiesjoint.azurecr.io/nginx:latest"
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    hostname: nginx
    depends_on:
      - api
    restart: always
    ports:
      - '8080:80'
